ktor:
    application:
        modules:
            - ua.nure.ApplicationKt.module
    deployment:
        port: 8080
storage:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: "jdbc:postgresql://127.0.0.1:5432/light"
  user: "light"