services:
  api:
    build: .
    container_name: smartLight
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/light
      DB_USER: light
      DB_PASSWORD: Secret1
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:18
    container_name: postgres-db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: light
      POSTGRES_USER: light
      POSTGRES_PASSWORD: Secret1
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U light" ]
      interval: 1s

volumes:
  pgdata: